/**
 * `opencoo setup` (PR 30 / plan #135 decision Q5).
 *
 * One-time bootstrap: prompts the operator for the minimal env
 * vars + writes them to `./.env` (gitignored, mode 0600). The
 * docker-compose.yml stays operator-owned — `setup` doesn't
 * generate it.
 *
 * Vars prompted:
 *   - DATABASE_URL (required)
 *   - REDIS_URL (required)
 *   - ENCRYPTION_KEY (required, 32-byte base64; CLI generates a
 *     fresh one if the operator confirms)
 *   - PORT (optional, default 8080)
 *   - GITEA_URL (required for engine-ingestion's wiki transport)
 *   - ADMIN_TEAM_SLUG (required for the admin-API)
 *   - SESSION_HMAC_KEY (required, generated)
 *   - GITEA_BASE_URL (required for the admin-API's whoami)
 *
 * The .env is written atomically (write-tmp + rename) so a
 * crashed run doesn't leave a partial file. Mode 0600 means
 * only the file's owner can read it — important because the
 * file holds secrets.
 *
 * Non-interactive (--yes) mode: every prompt resolves to its
 * default; required-without-default fails with a clear message.
 * That mode is for CI seeding only; production setup goes
 * through the interactive prompts.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import pc from "picocolors";
import promptsLib from "prompts";

import { exitOk, exitUserError } from "../lib/exit.js";

export interface SetupArgs {
  readonly cwd: string;
  readonly env: Record<string, string | undefined>;
  readonly nonInteractive: boolean;
  readonly stdout: { write: (s: string) => boolean };
  readonly stderr: { write: (s: string) => boolean };
  /** @internal Test seam — defaults to the `prompts` lib. */
  readonly promptsFn?: typeof promptsLib;
  /** @internal Test seam — defaults to `crypto.randomBytes`. */
  readonly randomBytes?: (n: number) => Buffer;
  /** @internal Test seam — defaults to `fs.writeFileSync`. */
  readonly writeFile?: (p: string, data: string, mode: number) => void;
  /** @internal Test seam — defaults to `fs.existsSync`. */
  readonly existsSync?: (p: string) => boolean;
}

interface CollectedAnswers {
  readonly databaseUrl: string;
  readonly redisUrl: string;
  readonly encryptionKey: string;
  readonly port: string;
  readonly giteaUrl: string;
  readonly adminTeamSlug: string;
  readonly sessionHmacKey: string;
  readonly giteaBaseUrl: string;
}

function defaultEnvLine(key: string, value: string): string {
  // Quote-only when needed (value contains whitespace or
  // special chars). Most URLs don't, so unquoted is fine.
  if (/[\s"'\\#$`]/.test(value)) {
    return `${key}="${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"\n`;
  }
  return `${key}=${value}\n`;
}

function buildEnvFile(answers: CollectedAnswers): string {
  return [
    "# opencoo .env — generated by `opencoo setup`",
    "# Mode 0600 — keep this file private.",
    "",
    defaultEnvLine("DATABASE_URL", answers.databaseUrl),
    defaultEnvLine("REDIS_URL", answers.redisUrl),
    defaultEnvLine("ENCRYPTION_KEY", answers.encryptionKey),
    defaultEnvLine("PORT", answers.port),
    defaultEnvLine("GITEA_URL", answers.giteaUrl),
    defaultEnvLine("ADMIN_TEAM_SLUG", answers.adminTeamSlug),
    defaultEnvLine("SESSION_HMAC_KEY", answers.sessionHmacKey),
    defaultEnvLine("GITEA_BASE_URL", answers.giteaBaseUrl),
  ].join("");
}

export async function runSetup(args: SetupArgs): Promise<void> {
  const promptsFn = args.promptsFn ?? promptsLib;
  const randomBytes = args.randomBytes ?? crypto.randomBytes;
  const writeFile =
    args.writeFile ??
    ((p, data, mode): void => fs.writeFileSync(p, data, { mode }));
  const existsSync = args.existsSync ?? ((p): boolean => fs.existsSync(p));

  const envPath = path.resolve(args.cwd, ".env");
  if (existsSync(envPath) && !args.nonInteractive) {
    args.stderr.write(
      pc.yellow(`setup: ${envPath} already exists; refusing to overwrite\n`),
    );
    args.stderr.write(pc.dim("setup: rename or remove the existing .env, then re-run\n"));
    return exitUserError();
  }

  // In non-interactive mode every value falls back to the
  // existing env or a generated default. Required values that
  // can't be defaulted (DATABASE_URL, REDIS_URL, GITEA_URL,
  // ADMIN_TEAM_SLUG, GITEA_BASE_URL) fail loud.
  const generatedEncryption = randomBytes(32).toString("base64");
  const generatedHmac = randomBytes(32).toString("base64");

  if (args.nonInteractive) {
    const required = [
      "DATABASE_URL",
      "REDIS_URL",
      "GITEA_URL",
      "ADMIN_TEAM_SLUG",
      "GITEA_BASE_URL",
    ] as const;
    const missing = required.filter(
      (k) => typeof args.env[k] !== "string" || args.env[k]?.length === 0,
    );
    if (missing.length > 0) {
      args.stderr.write(
        pc.red(
          `setup: --yes requires every required var in env; missing: ${missing.join(", ")}\n`,
        ),
      );
      return exitUserError();
    }
    const answers: CollectedAnswers = {
      databaseUrl: args.env["DATABASE_URL"]!,
      redisUrl: args.env["REDIS_URL"]!,
      encryptionKey: args.env["ENCRYPTION_KEY"] ?? generatedEncryption,
      port: args.env["PORT"] ?? "8080",
      giteaUrl: args.env["GITEA_URL"]!,
      adminTeamSlug: args.env["ADMIN_TEAM_SLUG"]!,
      sessionHmacKey: args.env["SESSION_HMAC_KEY"] ?? generatedHmac,
      giteaBaseUrl: args.env["GITEA_BASE_URL"]!,
    };
    writeFile(envPath, buildEnvFile(answers), 0o600);
    args.stdout.write(pc.green(`setup: wrote ${envPath} (mode 0600)\n`));
    return exitOk();
  }

  // Interactive path.
  const responses = await promptsFn([
    {
      type: "text",
      name: "databaseUrl",
      message: "DATABASE_URL",
      initial: args.env["DATABASE_URL"] ?? "postgres://opencoo:opencoo@localhost:5432/opencoo",
    },
    {
      type: "text",
      name: "redisUrl",
      message: "REDIS_URL",
      initial: args.env["REDIS_URL"] ?? "redis://localhost:6379",
    },
    {
      type: "text",
      name: "encryptionKey",
      message: "ENCRYPTION_KEY (32-byte base64) — leave blank to generate",
      initial: "",
    },
    {
      type: "text",
      name: "port",
      message: "PORT",
      initial: args.env["PORT"] ?? "8080",
    },
    {
      type: "text",
      name: "giteaUrl",
      message: "GITEA_URL (engine-ingestion wiki transport)",
      initial: args.env["GITEA_URL"] ?? "",
    },
    {
      type: "text",
      name: "adminTeamSlug",
      message: "ADMIN_TEAM_SLUG (Gitea team for admin authz)",
      initial: args.env["ADMIN_TEAM_SLUG"] ?? "opencoo-admins",
    },
    {
      type: "text",
      name: "sessionHmacKey",
      message: "SESSION_HMAC_KEY — leave blank to generate",
      initial: "",
    },
    {
      type: "text",
      name: "giteaBaseUrl",
      message: "GITEA_BASE_URL (admin-API whoami)",
      initial: args.env["GITEA_BASE_URL"] ?? "",
    },
  ]);

  // Operator cancelled (Ctrl-C) — `prompts` resolves missing
  // keys when interrupted.
  if (responses["databaseUrl"] === undefined) {
    args.stderr.write(pc.dim("setup: cancelled\n"));
    return exitUserError();
  }

  const answers: CollectedAnswers = {
    databaseUrl: String(responses["databaseUrl"] ?? ""),
    redisUrl: String(responses["redisUrl"] ?? ""),
    encryptionKey:
      String(responses["encryptionKey"] ?? "").length > 0
        ? String(responses["encryptionKey"])
        : generatedEncryption,
    port: String(responses["port"] ?? "8080"),
    giteaUrl: String(responses["giteaUrl"] ?? ""),
    adminTeamSlug: String(responses["adminTeamSlug"] ?? ""),
    sessionHmacKey:
      String(responses["sessionHmacKey"] ?? "").length > 0
        ? String(responses["sessionHmacKey"])
        : generatedHmac,
    giteaBaseUrl: String(responses["giteaBaseUrl"] ?? ""),
  };
  writeFile(envPath, buildEnvFile(answers), 0o600);
  args.stdout.write(pc.green(`setup: wrote ${envPath} (mode 0600)\n`));
  args.stdout.write(
    pc.dim(
      "setup: run `opencoo migrate` next; then `opencoo doctor` to verify.\n",
    ),
  );
  return exitOk();
}
